/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'branch' : IDL.Text,
  'contact' : IDL.Opt(IDL.Text),
  'nickname' : IDL.Text,
  'interests' : IDL.Opt(IDL.Text),
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'state' : IDL.Text,
});
export const ProfileResult = IDL.Variant({
  'ok' : UserProfile,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'createOrUpdateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [ProfileResult],
      [],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getRecentlyJoined' : IDL.Func([IDL.Nat], [IDL.Vec(UserProfile)], ['query']),
  'getUsersByFilters' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getUsersByState' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'branch' : IDL.Text,
    'contact' : IDL.Opt(IDL.Text),
    'nickname' : IDL.Text,
    'interests' : IDL.Opt(IDL.Text),
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'state' : IDL.Text,
  });
  const ProfileResult = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  
  return IDL.Service({
    'createOrUpdateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [ProfileResult],
        [],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getRecentlyJoined' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getUsersByFilters' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getUsersByState' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };